### PR TITLE
Release v0.1.1

### PR DESCRIPTION
**Pull request by listepo**
[FEATURE] Added Bearer Token Authentication
[#81](https://github.com/waterlock/waterlock/pull/81)

### CODE REVIEW

**Comment by listepo** [comment]
Ping

**Comment by davidrivera** [comment]
Nice! :+1:

**Comment by listepo** [comment]
You can publish it in npm?

**Comment by davidrivera** [comment]
we may publish this weekend

**Comment by listepo** [comment]
Ok :+1:

**Comment by listepo** [comment]
Ping

**Comment by listepo** [comment]
When npm will be published?

**Pull request merged**
